services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/develop/Dockerfile
    volumes:
      - ./:/go/src/go-restapi
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    platform: linux/x86_64
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD" ]
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 30s
volumes:
  dbdata:
