// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Tanakaryuki/go-restapi/internal/app/handler"
	task3 "github.com/Tanakaryuki/go-restapi/internal/app/handler/task"
	"github.com/Tanakaryuki/go-restapi/internal/app/repository/task"
	task2 "github.com/Tanakaryuki/go-restapi/internal/app/service/task"
	"github.com/Tanakaryuki/go-restapi/pkg/db"
)

// Injectors from wire.go:

func InitHandler() *handler.Root {
	sqlxDB := db.New()
	iRepository := task.New(sqlxDB)
	taskIService := task2.New(iRepository)
	taskHandler := task3.New(taskIService)
	root := handler.New(taskHandler)
	return root
}
